version: '3'

services:
  # ICE server, service port: 3478/udp and 3478/tcp
  coturn:
    build: coturn
    image: hub.docker.waypal.cn/waypal-coturn:1.0
    restart: always
    hostname: waypal-coturn
    network_mode: host
    ports:
      - 172.17.101.173:3478:3478
    environment:
      - SERVICE_NAME=waypal-coturn
      - SERVICE_TAGS=private_ip:172.17.101.173,public_ip:39.106.161.145,city:Hangzhou,region:Zhejiang,region_code:33,country:CN,country_name:China,postal:null,latitude:30.2936,longitude:120.1614,timezone:Asia/Shanghai,asn:AS37963,
      - SERVICE_REGION=DEV
     
  # KMS Server
  kms:
    build: kms
    image: hub.docker.waypal.cn/waypal-kms:1.0
    restart: always
    hostname: waypal-kms
    depends_on:
      - "coturn"
      - "telegraf"
      - "kmonitor"
      - "registrator"
    #network_mode: host
    ports:
      - 172.17.101.173:18888:8888
    volumes:
      - /home/waypal/volume/kms-cluster/kms/kms-media:/tmp
    environment:
      - GST_DEBUG=Kurento*:4
      - SERVICE_NAME=waypal-kms
      - SERVICE_TAGS=private_ip:172.17.101.173,public_ip:39.106.161.145,city:Hangzhou,region:Zhejiang,region_code:33,country:CN,country_name:China,postal:null,latitude:30.2936,longitude:120.1614,timezone:Asia/Shanghai,asn:AS37963,
      - SERVICE_REGION=DEV

  #telegraf
  telegraf:
    build: telegraf
    image: hub.docker.waypal.cn/waypal-telegraf:1.0
    restart: always
    hostname: waypal-telegraf
    network_mode: host
    volumes:
      - /home/waypal/volume/kms-cluster/monitor/telegraf/etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  # Kms Monitor Client
  kmonitor:
    build: ./kmonitor
    restart: always
    network_mode: host
    environment:
      - KMS_URI=ws://172.17.101.173:8888/kurento
      - KMS_NAME=waypal-docker-dev
      - GRAPHITE_IP=172.17.101.170
      - GRAPHITE_PORT=12003

  # Registrator (register container as services in Consul)
  registrator:
    build: registrator
    image: hub.docker.waypal.cn/waypal-registrator:1.0
    restart: always
    hostname: waypal-registrator
    command: -ip 172.17.101.173 consul://172.17.101.173:8500
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
      - SERVICE_IGNORE=true 

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
